stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ymeteor
      pushRemote: true
      registry: rg.fr-par.scw.cloud/youslide
timeout: 60
notification: {}
